# Generated by Django 4.2.13 on 2024-05-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='medicine',
        ),
        migrations.RemoveField(
            model_name='note',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='label',
        ),
        migrations.AddField(
            model_name='note',
            name='dosing_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='note',
            name='repeat',
            field=models.TextField(default='daily'),
        ),
    ]
