# Generated by Django 4.2.13 on 2024-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_title_note_medicine_remove_note_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='container',
            field=models.IntegerField(null=True),
        ),
    ]
